### ISSUE TITLE
For Follower PID Tuning Page, there are no instruction/videos for tank drive, can those be added, please?

### ISSUE THREAD

**Issue by farhadnbps** [NoahBres/LearnRoadRunner#13]

**Comment by NoahBres** [comment]
Tank drive is not a popular implementation at the moment. I personally don't have experience with it thus cannot offer any advice. My hope is to spend a weekend configuring a tank drive from scratch so I can make a tank drive guide. However, I cannot do so at the moment. There are a small number of people who have used tank drive with Road Runner in the FTC Discord server. I recommend you ask about their experience there.

**Comment by farhadnbps** [comment]
Thank you for the advice!

**Comment by NoahBres** [comment]
:D
I hope to get around to the tank guide eventually! However, a bit swamped with uni right now so it may take some time. The process for tank should be fairly similar to mecanum though! 

Asking here may help! https://discord.gg/first-tech-challenge
