### ISSUE TITLE
Forward offset in three wheel odometry section

### ISSUE THREAD

**Issue by ftcteam8645** [NoahBres/LearnRoadRunner#4]
Isn't the value for Forward Offset in the three wheel odometry section supposed to be the distance from the center of rotation vs the distance from the left and right wheels?

**Comment by NoahBres** [comment]
That is a good point. The road-runner-quickstart simply describes the forward offset in the same way. However, that naively assumes that the parallel odometry wheels are aligned with the center of rotation. Thanks for pointing this out! I never even thought about it like that :P

**Comment by NoahBres** [comment]
Fixed in 36882a150f99c6fae4d426e6829213ce84531abb
