### ISSUE TITLE
Can you stop a trajectory in the middle when a switch is hit?

### ISSUE THREAD

**Issue by freddysuede** [NoahBres/LearnRoadRunner#59]
We want to move the robot forward to pick up an element/game piece and then stop when a switch is activated (indicating the part is in contact) ...and then move onto another trajectory. Can you stop a trajectory in the middle when a switch is hit?

**Comment by NoahBres** [comment]
https://youtu.be/Kn_eRm8zV2Y
https://learnroadrunner.com/advanced.html#interrupting-a-live-trajectory
