### ISSUE TITLE
nextjs rewrite

### ISSUE THREAD

**Issue by NoahBres** [NoahBres/LearnRoadRunner#70]

**Comment by aleksrutins** [comment]
I would recommend [Nextra](https://nextra.site/) for docs; I don't know if that was already what you were thinking of, but if not, here it is.

**Comment by NoahBres** [comment]
![CleanShot 2023-03-08 at 20 14 30@2x](https://user-images.githubusercontent.com/6739076/223889728-1517e606-8696-4992-ba5d-b5b1f1282657.jpg)

I actually started a nextra rewrite back in December 👀
